### ISSUE TITLE
DeFi CustomTx scripting

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfish#108]
> This tracks all the DeFi scripting (AKA CustomTx) that is to be implemented in jellyfish-transaction.

```
packages/jellyfish-transaction/src/script/defi/*
```

All CustomTX has a starting signature of `DfTx` in utf8 or `0x44665478`. It is as it is, don't need to convert from BE to LE.

They are structured as a 
1. `VarUInt` + [`OP_RETURN` + `DfTx` + `TYPES[CxTxType]` + ...]
1. `VarUInt` + `6a` + `44665478` + Type + ...

## CustomTx
> It's a char, UTF8 -> HEX

- [x] createMasternode: `'C'` @ivan-zynesis #283
- [x] resignMasternode: `'R'` @ivan-zynesis #283
- [x] createToken: `'T'` @canonbrother #208
- [x] mintToken: `'M'` @canonbrother #170
- [x] updateToken: `'N'` @canonbrother #300
- [x] updateTokenAny: `'n'` @canonbrother #300
- [x] createPoolPair: `'p'` @canonbrother #233
- [x] updatePoolPair: `'u'` @canonbrother #314 
- [x] poolSwap: `'s'` @fuxingloh #143
- [x] addPoolLiquidity: `'l'` @fuxingloh #145
- [x] removePoolLiquidity: `'r'` @fuxingloh  #146
- [x] utxosToAccount: `'U'` @ivan-zynesis #175 
- [x] accountToUtxos: `'b'` @ivan-zynesis #175 
- [x] accountToAccount: `'B'` @ivan-zynesis #175 
- [x] setGovVariable: `'G'` @ivan-zynesis #298
- [x] anyAccountsToAccounts: `'a'` @ivan-zynesis #181
- [x] AutoAuthPrep: `'A'`, @ivan-zynesis #279

**Comment by fuxingloh** [comment]
https://github.com/DeFiCh/ain/pull/287/files

Oracles and AuthAuth

```c++
    AutoAuthPrep       = 'A',
    // oracles
    AppointOracle         = 200,
    RemoveOracleAppoint   = 201,
    UpdateOracleAppoint   = 202,
    SetOracleData         = 203,
```

**Comment by fuxingloh** [comment]
Check out #146 it's a good example on how to create DfTx

**Comment by ivan-zynesis** [comment]
Start working on.
- utxosToAccount: 'U'
- accountToUtxos: 'b'
- accountToAccount: 'B'
- anyAccountsToAccounts: 'a'

Hopefully can get clear mental picture and estimate time needed soon.

**Comment by canonbrother** [comment]
Working on createToken: 'T' (missed update)

**Comment by canonbrother** [comment]
Working on createPoolPair: 'p'

**Comment by ivan-zynesis** [comment]
Start working on: AutoAuthPrep: 'A'
