### ISSUE TITLE
`DeFiCh/ain:1.7.x` RPCs implementation

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfish#202]
Similar to https://github.com/DeFiCh/jellyfish/issues/48 This tracks all the RPC methods and categories being implemented in `jellyfish-api-core`. Please tag update this if you want to work on a feature.

~~As a final docker build is not produced please use the latest 1.7.x docker build for your `testcontainers`, https://github.com/DeFiCh/jellyfish/pull/184 for more information.~~

### `rpc_icxorderbook.cpp`
- [x] icx_createorder @surangap #398 
- [x] icx_makeoffer @surangap #399 
- [x] icx_closeoffer @surangap #400 
- [x] icx_submitdfchtlc @surangap #404 
- [x] icx_submitexthtlc @surangap #405 
- [x] icx_claimdfchtlc @surangap #406 
- [x] icx_closeorder @surangap #408 
- [x] icx_getorder @surangap #401 
- [x] icx_listorders @surangap #402 
- [x] icx_listhtlcs @surangap #407 

### `rpc_oracles.cpp`
- [x] appointoracle @jingyi2811 #336 
- [x] removeoracle @jingyi2811 #339 
- [x] updateoracle @jingyi2811  #341 
- [x] setoracledata @jingyi2811 #346
- [x] getoracledata @jingyi2811 #347
- [x] listoracles @jingyi2811 #345
- [x] listlatestrawprices @jingyi2811 #352 
- [x] getprice @jingyi2811 #355
- [x] listprices @jingyi2811 #356

### `spv_rpc.cpp`
- [x] spv_createhtlc @Jouzo #511
- [x] spv_claimhtlc @Jouzo #521
- [x] spv_gethtlcseed @Jouzo  #527
- [x] spv_refundhtlc @Jouzo #529
- [x] spv_listhtlcoutputs @Jouzo #581
- [x] spv_decodehtlcscript @Jouzo #513
- [x] spv_getnewaddress @Jouzo #495 
- [x] spv_getaddresspubkey @Jouzo #496
- [x] spv_listreceivedbyaddress @Jouzo #498
- [x] spv_sendtoaddress @Jouzo  #506
- [x] spv_refundhtlcall @cwkang1998 #1324

**Comment by surangap** [comment]
## `src/masternodes/`
### `rpc_accounts.cpp`
- [ ] listburnhistory
- [ ] getburninfo

### `rpc_icxorderbook.cpp`
- [ ] icx_createorder
- [ ] icx_makeoffer
- [ ] icx_closeoffer
- [ ] icx_submitdfchtlc
- [ ] icx_submitexthtlc
- [ ] icx_claimdfchtlc
- [ ] icx_closeorder
- [ ] icx_getorder
- [ ] icx_listorders
- [ ] icx_listhtlcs

### `rpc_oracles.cpp`
- [ ] appointoracle
- [ ] removeoracle
- [ ] updateoracle
- [ ] setoracledata
- [ ] getoracledata
- [ ] listoracles
- [ ] listlatestrawprices
- [ ] getprice
- [ ] listprices

### `rpc_tokens.cpp`
- [ ] decodecustomtx

## `src/spv/`
### `spv_rpc.cpp`
- [ ] spv_getfeerate

**Comment by jingyi2811** [comment]
Working on appointoracle

**Comment by jingyi2811** [comment]
Once the pagination feature is added to the C++ code, I need to open back the merged tickets and add test unit accordingly too

**Comment by Jouzo** [comment]
Reopened to handle #686

**Comment by cwkang1998** [comment]
@fuxingloh Closing this as its completed. If there's any new addition please do reopen it.
