### ISSUE TITLE
`DeFiCh/ain:2.x.x` Loan DfTx

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfish#532]
> Similar to https://github.com/DeFiCh/jellyfish/issues/108, this issue tracks the implementation of custom DfTx in `jellyfish-transaction` and `jellyfish-transaction-builder`. Must implement in `jellyfish-transaction` and test in `jellyfish-transaction-builder` for each PR.

### Loan DfTX

- [x] createLoanScheme: `'L'` @jingyi2811 #560
- [x] updateLoanScheme: `'L'` @jingyi2811 #591
- [x] setDefaultLoanScheme: `'d'` @jingyi2811 #592
- [x] destroyLoanScheme: `'D'` @jingyi2811 #594
- [x] setCollateralToken: `'c'` @jingyi2811 #619
- [x] setLoanToken: `'g'` @jingyi2811 #587 
- [x] updateLoanToken: `'f'` @jingyi2811 #588
- [x] createVault: `'V'` @surangap  #582
- [x] updateVault: `'v'` @jingyi2811 #701 
- [x] depositToVault `'S'` @surangap https://github.com/DeFiCh/jellyfish/pull/705
- [x] withdrawfromvault `'J'` @ivan-zynesis #750  
- [x] auctionBid `'I'` @canonbrother #722 
- [x] takeLoan `'X'` @surangap https://github.com/DeFiCh/jellyfish/pull/719
- [x] loanPayBack `'H'` @canonbrother #782 
- [x] closeVault `'e'` @jingyi2811 #731
- [x] setGovVariableHeight @ivan-zynesis #790
- [x] compositeswap @ivan-zynesis #779 
---
We have composite swap and perhaps other smaller DfTx in FC, we need to check them.
